### ISSUE TITLE
Cummulative energy charged not working on IONIQ...

### ISSUE THREAD

**Issue by Pazekal90** [EVNotify/EVNotifyPWA#34]
![image](https://user-images.githubusercontent.com/25208775/61189553-5f3edc00-a68f-11e9-8589-54ac526ebc0d.png)

I have already charged in the last two days and have already some charging logs.

**Comment by GPlay97** [comment]
Which version are you using? Or are you using PnP? Currently it's only available for the app. Update for PnP devices will come soon.

**Comment by Pazekal90** [comment]
The PnP Version :) I recommend some information Icons that describe why some values are not present at the moment and that this will come soon. PnP Users that spent a lot of money are not informed 100% and maybe are disappointed. 

I will add some of those informations if thats ok for you, soon. i would leave this issue open till then.

**Comment by GPlay97** [comment]
Keep in mind: The app is not the same like the web interface or the PnP devices.

App, especially in Beta channel, retrieves frequently new features, that could also be experimental and not stable. The new web interface (this repository) is also quite often updated (currently many things are on backlog, because app has priority), but still not completely the same. Many features will be added only, once they are stable.

For PnP devices: The idea behind them is to deliver a product, that works out of the box. To achieve this, updates are quite rarely to prevent breaking something. This is the "disadvantage" of having such a system. Of course, updates will follow, but they will only be added, once they are stable, and orders from the queue are processed.

To the web interface it was just added now.
